### ISSUE TITLE
rightclick holds left click

### ISSUE THREAD

**Issue by bjorn-beatso** [Beatso1/SimpleAutoClicker#10]
> This issue was created by an automation. It was authored in Discord by Nigelrex#8452, in Beatserver #feedback-support.

**Comment by r-rajaneesh** [comment]
yes i am here

**Comment by Beatso** [comment]
Is this a bug report? And what is the issue? Enabling the hold right click function holds left click?

**Comment by Beatso** [comment]
> needs to add just one word in the code

@Nigelrex if you'd like to suggest an improvement to the code, please [open a pull request](https://github.com/Beatso/SimpleAutoClicker/compare).

**Comment by r-rajaneesh** [comment]
ok sure just a sec

**Comment by Beatso** [comment]
https://user-images.githubusercontent.com/39217836/112827988-07c0e980-9087-11eb-8af7-c6e283a661f8.mp4

I'm unable to reproduce this - when I select hold right click, it works as expected by holding right click, and pressing left click on an interval. (v2.2.7)
